/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>
#include <progress2>
//Requires "progress2" include by Southclaws
//Download: https://github.com/Southclaws/progress2/releases

new PlayerText:HBE[MAX_PLAYERS];
new PlayerText:HBEGARISATAS[MAX_PLAYERS];
new PlayerText:HBEGARISKIRI[MAX_PLAYERS];
new PlayerText:HBEGARISBAWAH[MAX_PLAYERS];
new PlayerText:HBERCASH[MAX_PLAYERS];
new PlayerText:HBETCASH[MAX_PLAYERS];
new PlayerText:HBERDTFOOD[MAX_PLAYERS];
new PlayerText:HBERDDINK[MAX_PLAYERS];
new PlayerText:HBERPISS[MAX_PLAYERS];
new PlayerBar:HBEBARFOOD[MAX_PLAYERS];
new PlayerBar:HBEBARDRINK[MAX_PLAYERS];
new PlayerBar:HBEBARPISS[MAX_PLAYERS];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	HBE[playerid] = CreatePlayerTextDraw(playerid, 587.000000, 347.000000, "_");
	PlayerTextDrawFont(playerid, HBE[playerid], 1);
	PlayerTextDrawLetterSize(playerid, HBE[playerid], 0.600000, 10.300003);
	PlayerTextDrawTextSize(playerid, HBE[playerid], 298.500000, 98.000000);
	PlayerTextDrawSetOutline(playerid, HBE[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBE[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBE[playerid], 2);
	PlayerTextDrawColor(playerid, HBE[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBE[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBE[playerid], 135);
	PlayerTextDrawUseBox(playerid, HBE[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBE[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBE[playerid], 0);

	HBEGARISATAS[playerid] = CreatePlayerTextDraw(playerid, 588.000000, 347.000000, "_");
	PlayerTextDrawFont(playerid, HBEGARISATAS[playerid], 1);
	PlayerTextDrawLetterSize(playerid, HBEGARISATAS[playerid], 0.600000, 0.450002);
	PlayerTextDrawTextSize(playerid, HBEGARISATAS[playerid], 298.500000, 99.000000);
	PlayerTextDrawSetOutline(playerid, HBEGARISATAS[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEGARISATAS[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEGARISATAS[playerid], 2);
	PlayerTextDrawColor(playerid, HBEGARISATAS[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEGARISATAS[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEGARISATAS[playerid], 189);
	PlayerTextDrawUseBox(playerid, HBEGARISATAS[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBEGARISATAS[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEGARISATAS[playerid], 0);

	HBEGARISKIRI[playerid] = CreatePlayerTextDraw(playerid, 542.000000, 348.000000, "_");
	PlayerTextDrawFont(playerid, HBEGARISKIRI[playerid], 1);
	PlayerTextDrawLetterSize(playerid, HBEGARISKIRI[playerid], 0.600000, 10.400010);
	PlayerTextDrawTextSize(playerid, HBEGARISKIRI[playerid], 298.500000, 7.500000);
	PlayerTextDrawSetOutline(playerid, HBEGARISKIRI[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEGARISKIRI[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEGARISKIRI[playerid], 2);
	PlayerTextDrawColor(playerid, HBEGARISKIRI[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEGARISKIRI[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEGARISKIRI[playerid], 189);
	PlayerTextDrawUseBox(playerid, HBEGARISKIRI[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBEGARISKIRI[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEGARISKIRI[playerid], 0);

	HBEGARISBAWAH[playerid] = CreatePlayerTextDraw(playerid, 589.000000, 381.000000, "_");
	PlayerTextDrawFont(playerid, HBEGARISBAWAH[playerid], 1);
	PlayerTextDrawLetterSize(playerid, HBEGARISBAWAH[playerid], 0.600000, -0.599997);
	PlayerTextDrawTextSize(playerid, HBEGARISBAWAH[playerid], 298.500000, 102.000000);
	PlayerTextDrawSetOutline(playerid, HBEGARISBAWAH[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEGARISBAWAH[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEGARISBAWAH[playerid], 2);
	PlayerTextDrawColor(playerid, HBEGARISBAWAH[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEGARISBAWAH[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEGARISBAWAH[playerid], 178);
	PlayerTextDrawUseBox(playerid, HBEGARISBAWAH[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBEGARISBAWAH[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEGARISBAWAH[playerid], 0);

	HBERCASH[playerid] = CreatePlayerTextDraw(playerid, 561.000000, 362.000000, "HUD:radar_cash");
	PlayerTextDrawFont(playerid, HBERCASH[playerid], 4);
	PlayerTextDrawLetterSize(playerid, HBERCASH[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBERCASH[playerid], 9.000000, 11.500000);
	PlayerTextDrawSetOutline(playerid, HBERCASH[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBERCASH[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBERCASH[playerid], 1);
	PlayerTextDrawColor(playerid, HBERCASH[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBERCASH[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBERCASH[playerid], 50);
	PlayerTextDrawUseBox(playerid, HBERCASH[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBERCASH[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBERCASH[playerid], 0);

	HBETCASH[playerid] = CreatePlayerTextDraw(playerid, 576.000000, 363.000000, "999,999.99");
	PlayerTextDrawFont(playerid, HBETCASH[playerid], 3);
	PlayerTextDrawLetterSize(playerid, HBETCASH[playerid], 0.320832, 0.999998);
	PlayerTextDrawTextSize(playerid, HBETCASH[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, HBETCASH[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBETCASH[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBETCASH[playerid], 1);
	PlayerTextDrawColor(playerid, HBETCASH[playerid], 9109759);
	PlayerTextDrawBackgroundColor(playerid, HBETCASH[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBETCASH[playerid], 50);
	PlayerTextDrawUseBox(playerid, HBETCASH[playerid], 0);
	PlayerTextDrawSetProportional(playerid, HBETCASH[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBETCASH[playerid], 0);

	HBERDTFOOD[playerid] = CreatePlayerTextDraw(playerid, 553.000000, 391.000000, "HUD:radar_datefood");
	PlayerTextDrawFont(playerid, HBERDTFOOD[playerid], 4);
	PlayerTextDrawLetterSize(playerid, HBERDTFOOD[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBERDTFOOD[playerid], 11.500000, 13.500000);
	PlayerTextDrawSetOutline(playerid, HBERDTFOOD[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBERDTFOOD[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBERDTFOOD[playerid], 1);
	PlayerTextDrawColor(playerid, HBERDTFOOD[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBERDTFOOD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBERDTFOOD[playerid], 50);
	PlayerTextDrawUseBox(playerid, HBERDTFOOD[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBERDTFOOD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBERDTFOOD[playerid], 0);

	HBERDDINK[playerid] = CreatePlayerTextDraw(playerid, 553.000000, 411.000000, "HUD:radar_datedrink");
	PlayerTextDrawFont(playerid, HBERDDINK[playerid], 4);
	PlayerTextDrawLetterSize(playerid, HBERDDINK[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBERDDINK[playerid], 11.500000, 13.500000);
	PlayerTextDrawSetOutline(playerid, HBERDDINK[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBERDDINK[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBERDDINK[playerid], 1);
	PlayerTextDrawColor(playerid, HBERDDINK[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBERDDINK[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBERDDINK[playerid], 50);
	PlayerTextDrawUseBox(playerid, HBERDDINK[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBERDDINK[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBERDDINK[playerid], 0);

	HBERPISS[playerid] = CreatePlayerTextDraw(playerid, 553.000000, 432.000000, "HUD:radar_centre");
	PlayerTextDrawFont(playerid, HBERPISS[playerid], 4);
	PlayerTextDrawLetterSize(playerid, HBERPISS[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBERPISS[playerid], 11.500000, 13.500000);
	PlayerTextDrawSetOutline(playerid, HBERPISS[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBERPISS[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBERPISS[playerid], 1);
	PlayerTextDrawColor(playerid, HBERPISS[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HBERPISS[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBERPISS[playerid], 50);
	PlayerTextDrawUseBox(playerid, HBERPISS[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBERPISS[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBERPISS[playerid], 0);

	HBEBARFOOD[playerid] = CreatePlayerProgressBar(playerid, 572.000000, 397.000000, 64.500000, -2.500000, 16711935, 100.000000, 0);
	SetPlayerProgressBarValue(playerid, HBEBARFOOD[playerid], 50.000000);

	HBEBARDRINK[playerid] = CreatePlayerProgressBar(playerid, 572.000000, 417.000000, 64.500000, -2.500000, 16711935, 100.000000, 0);
	SetPlayerProgressBarValue(playerid, HBEBARDRINK[playerid], 50.000000);

	HBEBARPISS[playerid] = CreatePlayerProgressBar(playerid, 572.000000, 437.000000, 64.500000, -2.500000, -1, 100.000000, 0);
	SetPlayerProgressBarValue(playerid, HBEBARPISS[playerid], 50.000000);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, HBE[playerid]);
	PlayerTextDrawDestroy(playerid, HBEGARISATAS[playerid]);
	PlayerTextDrawDestroy(playerid, HBEGARISKIRI[playerid]);
	PlayerTextDrawDestroy(playerid, HBEGARISBAWAH[playerid]);
	PlayerTextDrawDestroy(playerid, HBERCASH[playerid]);
	PlayerTextDrawDestroy(playerid, HBETCASH[playerid]);
	PlayerTextDrawDestroy(playerid, HBERDTFOOD[playerid]);
	PlayerTextDrawDestroy(playerid, HBERDDINK[playerid]);
	PlayerTextDrawDestroy(playerid, HBERPISS[playerid]);
	DestroyPlayerProgressBar(playerid, HBEBARFOOD[playerid]);
	DestroyPlayerProgressBar(playerid, HBEBARDRINK[playerid]);
	DestroyPlayerProgressBar(playerid, HBEBARPISS[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, HBE[playerid]);
		PlayerTextDrawShow(playerid, HBEGARISATAS[playerid]);
		PlayerTextDrawShow(playerid, HBEGARISKIRI[playerid]);
		PlayerTextDrawShow(playerid, HBEGARISBAWAH[playerid]);
		PlayerTextDrawShow(playerid, HBERCASH[playerid]);
		PlayerTextDrawShow(playerid, HBETCASH[playerid]);
		PlayerTextDrawShow(playerid, HBERDTFOOD[playerid]);
		PlayerTextDrawShow(playerid, HBERDDINK[playerid]);
		PlayerTextDrawShow(playerid, HBERPISS[playerid]);
		ShowPlayerProgressBar(playerid, HBEBARFOOD[playerid]);
		ShowPlayerProgressBar(playerid, HBEBARDRINK[playerid]);
		ShowPlayerProgressBar(playerid, HBEBARPISS[playerid]);
		return 1;
	}
	return 0;
}
